token:
#  secret: ${TOKEN_SECRET:your_base64_encoded_secret}
  keys: # key id 와 secret 을 담을 수 있는 구조만 정의
    key_v1:
      id: key_v1
      secret: ${TOKEN_KEY1_SECRET:your_base64_encoded_secret}
  current-key-id: key_v1
  validity:
    USER_ACCESS: 3600000        # 1시간
    USER_REFRESH: 604800000     # 7일
    PROFILE_ACCESS: 3600000     # 1시간
    PROFILE_REFRESH: 604800000  # 7일
    NONCE: 300000              # 5분


    ################
